version: '3.8'

services:
  aui-ims-robot:
    build: .
    container_name: aui-ims-robot
    ports:
      - "8881:8881"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # 可以在这里设置其他环境变量
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      # 如果需要挂载配置文件，可以使用以下配置
      # - ./config:/app/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8881/api/v2/aiagent/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge 